ARG ROS_DISTRO=foxy
FROM ros:${ROS_DISTRO}

ADD simulation_ws /root/ros2_ws
WORKDIR /root/ros2_ws/
RUN apt-get update && \ 
    . /opt/ros/foxy/setup.sh && \
    rosdep update && rosdep fix-permissions
RUN rosdep install --from src -i -y
RUN mkdir /opt/jetbot_simulation/
RUN apt update ** apt install ros-foxy-gazebo-plugins
RUN . /opt/ros/foxy/setup.sh && colcon build --install-base /opt/jetbot_ros/