version: "3"
services: 

  foxy:
    build: 
        context: ./
        dockerfile: Dockerfile.l4t.ros.foxy
        network: host
    image: ros-foxy-l4t-base:r32.4.4

  jetbot:
    build: 
        context: ./
        dockerfile: Dockerfile.robot
    image: jetbot-ros2:robot
    
  robot_app:
    network_mode: host
    container_name: robot
    image: jetbot-ros2:robot
    command: ros2 launch ${ROBOT_ROS_PKG} ${ROBOT_ROS_LAUNCH}.launch.py
    environment:
      - DEFAULT_SPEED=0.3

  simulation_app:
    network_mode: host
    container_name: simulation
    image: jetbot-ros2:simulation
    command: ros2 launch ${SIM_ROS_PKG} ${SIM_ROS_LAUNCH}.launch.py
    gpus: all
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - $HOME/.Xauthority:/root/.Xauthority
    environment:
        DISPLAY: $DISPLAY
        QT_X11_NO_MITSHM: 1
        NVIDIA_DRIVER_CAPABILITIES: all